export const projects = [
  {
    title: "FinMate",
    description: "FinMate is a comprehensive personal finance management application built with Flutter and FastAPI, designed to help users track, analyze, and manage their finances effortlessly.",
    imageUrl: "/projects/finmate.png",
    techStack: ["Flutter", "FastAPI", "Python", "Supabase", "Firebase"],
    liveUrl: "#",
    githubUrl: "https://github.com/HarshitBilagi/FinMate.git",
    live: false,
  },
  {
    title: "MNPI Agent",
    description: "An AI-powered agent that verifies documents for Material Non-Public Information (MNPI) using advanced NLP techniques to ensure compliance and mitigate risks.",
    imageUrl: "/projects/MNPI.png",
    techStack: ["Python"],
    liveUrl: "#",
    githubUrl: "https://github.com/HarshitBilagi/mnpi-agent.git",
    live: false,
  },
  {
    title: "LeetCode Revision Agent",
    description: "An agent that helps you revise solved LeetCode problems by sending you N number of solved problems with link everyday through mail.",
    imageUrl: "/projects/p1.png",
    techStack: ["Python"],
    liveUrl: "#",
    githubUrl: "https://github.com/HarshitBilagi/LeetCode-Revision-Agent",
    live: false,
  },
  {
    title: "BlogIt",
    description: "A blogging platform where users can create, edit, and share blog posts. A Full-Stack application with user authentication, authorization and responsive design.",
    imageUrl: "/projects/p2.png",
    techStack: ["Next.Js", "REST API", "Node.js", "Tailwind CSS", "MongoDB"],
    liveUrl: "#",
    githubUrl: "https://github.com/HarshitBilagi/blog-it",
    live: false,
  },
  {
    title: "Portfolio Website",
    description: "A modern, responsive portfolio website built with Next.js and Tailwind CSS to showcase projects, skills, and experience.",
    imageUrl: "/projects/p3.png",
    techStack: ["Next.Js", "TypeScript", "Tailwind CSS", "Framer Motion", "GSAP"],
    liveUrl: "https://my-portfolio-git-main-sirius-projects-9e638854.vercel.app/",
    githubUrl: "https://github.com/HarshitBilagi/my-portfolio",
    live: true,
  },
  {
    title: "Online FIR System",
    description: "This is a user side web application where a user can file a First Information Report (FIR) online, without the need of visiting police station physically.",
    imageUrl: "/projects/p4.png",
    techStack: ["HTML5", "CSS3", "JavaScript", "PHP", "MySQL"],
    liveUrl: "#",
    githubUrl: "https://github.com/HarshitBilagi/Online-FIR-System.git",
    live: false,
  },
  {
    title: "Customer Survey: A Kiosk Application",
    description: "A responsive customer survey form built with React that allows users to answer questions, stores results in Database, and uses 'useNavigate' for smooth redirection after submission.",
    imageUrl: "/projects/p5.png",
    techStack: ["React", "JavaScript"],
    liveUrl: "#",
    githubUrl: "https://github.com/HarshitBilagi/Customer_Survey",
    live: false,
  },
  {
    title: "To-Do List",
    description: "An efficient To-Do List application with full CRUD capabilities, allowing you to easily Create, Read, Update, and Delete tasks. Stay organized and manage your tasks seamlessly with this user-friendly task management system.",
    imageUrl: "/projects/p6.png",
    techStack: ["HTML5", "CSS3", "JavaScript"],
    liveUrl: "#",
    githubUrl: "https://github.com/HarshitBilagi/To-Do-List",
    live: false,
  },
];